/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/clusters` | `/clusters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/constellation` | `/constellation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/inbox` | `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/develop/[id]` | `/develop/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/clusters` | `/clusters`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/constellation` | `/constellation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/inbox` | `/inbox`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/develop/[id]` | `/develop/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/clusters${`?${string}` | `#${string}` | ''}` | `/clusters${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/constellation${`?${string}` | `#${string}` | ''}` | `/constellation${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/inbox${`?${string}` | `#${string}` | ''}` | `/inbox${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/clusters` | `/clusters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/constellation` | `/constellation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/inbox` | `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `${'/(app)'}/develop/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/develop/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/develop/[id]` | `/develop/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
